project_id = "eialbbgpkyjjzcfkxbgc"

[functions]
  [functions.analyse-screenshot]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
