import { Helmet } from "react-helmet-async";
import LegalLayout from "@/components/LegalLayout";
import { Link } from "react-router-dom";

const CONTACT_EMAIL = "hello@unscreenshot.ai";

export default function Terms() {
  return (
    <LegalLayout title="Terms of Service" effectiveDate="May 2026">
      <Helmet>
        <title>Terms of Service — Unscreenshot</title>
        <meta name="description" content="Unscreenshot terms of service. Beta service terms, acceptable use, liability, and governing law." />
        <link rel="canonical" href="/legal/terms" />
        <meta property="og:title" content="Terms of Service — Unscreenshot" />
        <meta property="og:description" content="Unscreenshot terms of service. Beta service terms, acceptable use, liability, and governing law." />
        <meta property="og:url" content="https://unscreenshot.ai/legal/terms" />
        <meta property="og:type" content="article" />
      </Helmet>
      <p>
        By using Unscreenshot you agree to these terms. They're short on purpose.
      </p>

      <h2>The service</h2>
      <p>
        Unscreenshot is a beta tool that uses AI to turn screenshots into
        reminders. Beta means features change, things occasionally break, and
        availability is not guaranteed.
      </p>

      <h2>Your account</h2>
      <ul>
        <li>You must provide a valid email address and keep your password secure.</li>
        <li>One person per account. Don't share credentials.</li>
        <li>You must be at least 16 years old.</li>
      </ul>

      <h2>Acceptable use</h2>
      <p>Don't use Unscreenshot to:</p>
      <ul>
        <li>Upload content that is illegal, infringing, or that you don't have the right to share.</li>
        <li>Upload other people's private information (medical records, IDs, financial documents) without consent.</li>
        <li>Try to break, abuse, reverse-engineer, or overload the service.</li>
        <li>Spam others through the share-reminder feature.</li>
        <li>Build a competing service using our outputs.</li>
      </ul>
      <p>
        We may suspend or terminate accounts that violate these rules, with or
        without notice depending on severity.
      </p>

      <h2>Your content</h2>
      <p>
        You keep ownership of the screenshots you upload. You grant us a
        limited licence to store, process, and display them solely so we can
        run the service for you (including sending them to Anthropic for AI
        analysis and rendering them in reminder emails to people you share
        with). That licence ends when you delete the content or your account.
      </p>
      <p>
        Note that uploaded images are stored in a publicly-readable bucket —
        see the <Link to="/legal/privacy">Privacy Policy</Link> for details
        and the practical implications.
      </p>

      <h2>AI output</h2>
      <p>
        Titles, categories, and deadlines are generated by an AI model. They
        can be wrong. Review before relying on them. We're not liable for
        missed deadlines, mis-categorised reminders, or any decisions you make
        based on AI output.
      </p>

      <h2>Beta limits and changes</h2>
      <p>
        During beta we cap usage (currently 30 AI analyses per account) and
        may change features, pricing, or the service itself at any time. If
        we make a material change that affects you, we'll let you know.
      </p>

      <h2>No warranty</h2>
      <p>
        Unscreenshot is provided "as is" without warranties of any kind. We
        don't promise it will be error-free, secure, or always available.
      </p>

      <h2>Liability</h2>
      <p>
        To the extent permitted by law, our total liability to you for any
        claim related to the service is limited to the amount you have paid
        us in the 12 months before the claim — which during the beta is
        zero. We're not liable for indirect, incidental, or consequential
        damages.
      </p>

      <h2>Termination</h2>
      <p>
        You can delete your account at any time from the Account page. We can
        terminate your account if you breach these terms. On termination, your
        data is deleted as described in the Privacy Policy.
      </p>

      <h2>Governing law</h2>
      <p>
        These terms are governed by the laws of England and Wales. Any
        dispute arising out of or in connection with the service or these
        terms will be subject to the exclusive jurisdiction of the courts of
        England and Wales.
      </p>

      <h2>Contact</h2>
      <p>
        Questions: <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
      </p>
    </LegalLayout>
  );
}
